Watching for file changes with StatReloader
Invalid HTTP_HOST header: '59.110.140.64:8080'. You may need to add '59.110.140.64' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '59.110.140.64:8080'. You may need to add '59.110.140.64' to ALLOWED_HOSTS.
Bad Request: /postapp/
[15/Oct/2022 12:29:59] "GET /postapp/ HTTP/1.1" 400 61404
Invalid HTTP_HOST header: '59.110.140.64:8080'. You may need to add '59.110.140.64' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '59.110.140.64:8080'. You may need to add '59.110.140.64' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[15/Oct/2022 12:30:00] "GET /favicon.ico HTTP/1.1" 400 61160
/home/gp8/SE2022/myproject_v2/myproject/mysite/mysite/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 12:29:42
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[15/Oct/2022 12:32:22] "GET /postapp/ HTTP/1.1" 200 9100
Not Found: /favicon.ico
[15/Oct/2022 12:32:22] "GET /favicon.ico HTTP/1.1" 404 2222
[15/Oct/2022 12:32:25] "GET /postapp/logoutAction/ HTTP/1.1" 200 923
[15/Oct/2022 12:32:25] "GET /static/css/border01.css HTTP/1.1" 200 1223
[15/Oct/2022 12:32:31] "POST /postapp/loginAction/ HTTP/1.1" 200 994
[15/Oct/2022 12:32:47] "POST /postapp/loginAction/ HTTP/1.1" 200 9186
Not Found: /http:/azenv.net/
[15/Oct/2022 12:34:28] "GET http://azenv.net/ HTTP/1.1" 404 1790
[15/Oct/2022 12:35:10] "GET /postapp/27/detail/ HTTP/1.1" 200 1879
[15/Oct/2022 12:35:10] "GET /static/css/border02.css HTTP/1.1" 200 1429
[15/Oct/2022 12:35:19] "GET /postapp/ HTTP/1.1" 200 9186
[15/Oct/2022 12:35:21] "GET /postapp/27/detail/ HTTP/1.1" 200 1879
[15/Oct/2022 12:35:24] "GET /postapp/ HTTP/1.1" 200 9186
[15/Oct/2022 12:35:26] "GET /postapp/26/detail/ HTTP/1.1" 200 2918
[15/Oct/2022 12:35:29] "GET /postapp/ HTTP/1.1" 200 9186
Not Found: /
[15/Oct/2022 12:41:43] "GET / HTTP/1.1" 404 2171
Not Found: /http:/azenv.net/
[15/Oct/2022 12:42:46] "GET http://azenv.net/ HTTP/1.1" 404 1790
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[15/Oct/2022 12:48:53] "GET /manager/html HTTP/1.1" 400 59182
Not Found: /http:/azenv.net/
[15/Oct/2022 12:50:37] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 12:58:37] "GET http://azenv.net/ HTTP/1.1" 404 1790
[15/Oct/2022 13:07:16] "GET /postapp/ HTTP/1.1" 200 9186
Not Found: /http:/azenv.net/
[15/Oct/2022 13:10:37] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 13:18:44] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 13:26:38] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 13:34:45] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 13:42:39] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 13:50:34] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 13:58:38] "GET http://azenv.net/ HTTP/1.1" 404 1790
Not Found: /http:/azenv.net/
[15/Oct/2022 14:10:38] "GET http://azenv.net/ HTTP/1.1" 404 1790
/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 12:31:27
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 14:11:05
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[15/Oct/2022 14:12:51] "GET /postapp/ HTTP/1.1" 200 9186
[15/Oct/2022 14:12:54] "GET /postapp/26/detail/ HTTP/1.1" 200 2918
[15/Oct/2022 14:12:56] "GET /postapp/ HTTP/1.1" 200 9186
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.443 seconds.
Prefix dict has been built successfully.
Internal Server Error: /postapp/search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/views.py", line 138, in SearchMyPost
    obj_set.append(MyPost.objects.get(pk=pk))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
postapp.models.MyPost.DoesNotExist: MyPost matching query does not exist.
[15/Oct/2022 14:13:03] "POST /postapp/search/ HTTP/1.1" 500 68258
/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 14:12:47
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.431 seconds.
Prefix dict has been built successfully.
Internal Server Error: /postapp/search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/views.py", line 138, in SearchMyPost
    obj_set.append(MyPost.objects.get(pk=pk+1))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
postapp.models.MyPost.DoesNotExist: MyPost matching query does not exist.
[15/Oct/2022 14:14:26] "POST /postapp/search/ HTTP/1.1" 500 68262
/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 14:14:22
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/mysearch.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 14:15:42
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[15/Oct/2022 14:17:02] "GET /postapp/ HTTP/1.1" 200 9186
[15/Oct/2022 14:17:04] "GET /postapp/26/detail/ HTTP/1.1" 200 2918
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.441 seconds.
Prefix dict has been built successfully.
[15/Oct/2022 14:17:13] "POST /postapp/search/ HTTP/1.1" 200 9186
[15/Oct/2022 14:17:38] "POST /postapp/search/ HTTP/1.1" 200 9186
Not Found: /http:/azenv.net/
[15/Oct/2022 14:18:41] "GET http://azenv.net/ HTTP/1.1" 404 1790
/home/gp8/SE2022/myproject_v2/myproject/mysite/postapp/mysearch.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 15, 2022 - 14:16:55
Django version 4.1.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.445 seconds.
Prefix dict has been built successfully.
[15/Oct/2022 14:19:36] "POST /postapp/search/ HTTP/1.1" 200 9186
[15/Oct/2022 14:20:19] "POST /postapp/search/ HTTP/1.1" 200 9186
[15/Oct/2022 14:21:07,743] - Broken pipe from ('167.248.133.61', 59806)
Not Found: /
[15/Oct/2022 14:21:08] "GET / HTTP/1.1" 404 2171
[15/Oct/2022 14:21:09,216] - Broken pipe from ('167.248.133.61', 36852)
Not Found: /
[15/Oct/2022 14:21:09] "GET / HTTP/1.1" 404 2171
[15/Oct/2022 14:21:10] code 505, message Invalid HTTP version (2.0)
[15/Oct/2022 14:21:10] "PRI * HTTP/2.0" 505 -
